services:
  db:
    build:
      context: ../../backend/db/
      dockerfile: ../../backend/db/db.Dockerfile
    image: activitydetectordb
    container_name: ac_db
    volumes:
      - ac-data-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activitydetectordb
    ports:
      - "5433:5432"

  backend:
    build:
      context: ../../backend/backend/
      dockerfile: backend.Dockerfile
    image: activitydetectorbackend
    container_name: ac_backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ../../frontend/
      dockerfile: frontend.Dockerfile
    image: activitydetectorfrontend
    container_name: ac_frontend
    ports:
      - "4200:8080"
    depends_on:
      - backend

volumes:
  ac-data-vol:
